fixes:
  - "/home/runner/work/now_lms/::"
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
ignore:
  - "now_lms/__main__.py"
  - "now_lms/cli.py"
  - "now_lms/db/backup.py"
