site_name: NOW - LMS
theme:
    name: material
    language: es
    favicon: media/favicon.png
    logo: media/now_lms.png
    palette:
        accent: teal
    icon:
        repo: fontawesome/brands/git-alt
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.sections

repo_url: https://github.com/bmosoluciones/now-lms
repo_name: bmosoluciones/now-lms

copyright: Copyright &copy; 2021 - 2023 BMO Soluciones

nav:
    - Inicio: index.md
    - Setup: config.md
    - Python Package: pypi.md
    - Docker: oci.md
    - DreamHost: dreamhost.md
    - Server Setup:
      - CentOS / Alma / Rocky: rocky.md