# Copyright 2021 -2023 William José Moreno Reyes
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


"""Static routes definition for testing different user roles and expected responses."""

from types import SimpleNamespace


def Ruta(
    ruta: str,
    admin: int,
    no_session: int,
    user: int,
    moderator: int,
    instructor: int,
    texto: list,
    como_user: list,
    como_moderador: list,
    como_instructor: list,
    como_admin: list,
) -> SimpleNamespace:
    """Create a route test configuration using SimpleNamespace.

    Args:
        ruta: Route to test
        admin: Expected HTTP response for admin role
        no_session: Expected HTTP response for anonymous users
        user: Expected HTTP response for user role
        moderator: Expected HTTP response for moderator role
        instructor: Expected HTTP response for instructor role
        texto: Test text to compare against page content
        como_user: Text to verify when testing as user
        como_moderador: Text to verify when testing as moderator
        como_instructor: Text to verify when testing as instructor
        como_admin: Text to verify when testing as admin

    Returns:
        SimpleNamespace containing the route test configuration
    """
    return SimpleNamespace(
        ruta=ruta,
        admin=admin,
        no_session=no_session,
        user=user,
        moderator=moderator,
        instructor=instructor,
        texto=texto,
        como_user=como_user,
        como_moderador=como_moderador,
        como_instructor=como_instructor,
        como_admin=como_admin,
    )


"""
Example template to create a new route test:

Ruta(
    ruta="",
    no_session=100,
    admin=100,
    user=100,
    moderator=100,
    instructor=100,
    texto=[],
    como_user=[],
    como_moderador=[],
    como_instructor=[],
    como_admin=[],
),
"""

rutas_estaticas = [
    # <---------------------------------------------------------------------> #
    # Home page
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/home",
        admin=200,
        no_session=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[
            "NOW LMS".encode("utf-8"),
            "Aprende con Nosotros".encode("utf-8"),
            "This is your first course.".encode("utf-8"),
        ],
        como_user=[b"Dania", b"Mendez"],
        como_moderador=[b"Abner", b"Romero"],
        como_instructor=[b"Nemesio", b"Reyes"],
        como_admin=[
            "Cerrar Sesión".encode("utf-8"),
            "Administración".encode("utf-8"),
            b"System",
            b"Administrator",
            "Manual de Administración".encode("utf-8"),
        ],
    ),
    # <---------------------------------------------------------------------> #
    # Keep in the same order that the url_map:
    #     >>> from now_lms import app
    #     >>> app.url_map
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/category/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/category/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/category/01HNP0TTQNTR03J7ZQHR09YMJK/edit",  # Hard coded ULID in test data creation
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/category/01HNP0TTQNTR03J7ZQHR09YMJK/delete",
        no_session=302,
        admin=302,  # Delete return a redirect
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/certificate/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[
            b"Crear nuevo Certificado.",
            b"Certificado",
            b"Descripcion",
            b"Crear Certificado",
            b"""<button class="w-10 btn btn-lg btn-primary btn-block" type="submit">Crear Certificado</button>""",
        ],
    ),
    Ruta(
        ruta="/certificate/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[
            b"Lista de Certificados Disponibles.",
            b"Lista de certificados disponibles en el sistema.",
            b"Certficado Test",
            b"Nuevo Certificado",
        ],
        como_instructor=[],
        como_admin=[
            b"Lista de Certificados Disponibles.",
            b"Lista de certificados disponibles en el sistema.",
            b"Certficado Test",
            b"Nuevo Certificado",
        ],
    ),
    Ruta(
        ruta="/certificate/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[
            b"Editar Certificado.",
            b"Certficado Test",
            b"Actualizar Certificado",
            b"Habilitado",
            b"Certificado Test",
        ],
    ),
    Ruta(
        ruta="/certificate/1234567890/edit",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[
            b"Editar Certificado.",
            b"Certficado Test",
            b"Actualizar Certificado",
            b"Habilitado",
            b"Certificado Test",
        ],
    ),
    Ruta(
        ruta="/certificate/1234567890/remove",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/certificate/1234567890/add",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/certificate/1234567890/publish",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/certificate/1234567890/unpublish",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/instructor/courses_list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[b"Inscribirse al Curso"],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/view",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[b"Inscribirse al Curso"],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/view?inspect=True",
        no_session=200,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[b"Inscribirse al Curso"],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/enroll",
        no_session=302,
        admin=200,
        user=200,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[b"Inscribirse al Curso"],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/take",
        no_session=302,
        admin=302,
        user=200,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/moderate",
        no_session=302,
        admin=200,
        user=403,
        moderator=200,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/admin",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/new_curse",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/edit",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/new_seccion",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/01HPB1MZXBHZETC4ZH0HV4G39Q/edit",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/seccion/increment/1",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/seccion/decrement/2",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/resource/now/01HPB1MZXBHZETC4ZH0HV4G39Q/increment/1",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/resource/now/01HPB1MZXBHZETC4ZH0HV4G39Q/decrement/2",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/delete_recurso/01HPB1MZXBHZETC4ZH0HV4G39Q/01HPB3AP3QNVK9ES6JGG5YK7CH",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/change_curse_status?curse=now&status=draft",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/change_curse_public?curse=now",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/change_curse_seccion_public?course_code=now&codigo=01HPB1MZXBHZETC4ZH0HV4G39Q",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/delete_seccion/01HPB1MZXBHZETC4ZH0HV4G39Q",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/now/description",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/course/explore",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/group/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/panel",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/home/panel",
        no_session=302,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/program/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/program/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/program/explore",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/program/01HNZXEMSWTSBM4PNSY4R9VMN6/edit",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/program/01HNZXEMSWTSBM4PNSY4R9VMN6/delete",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/resource/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/resource/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/resource/01HNZXA1BX9B297CYAAA4MK93V/donwload",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/resource/01HNZXA1BX9B297CYAAA4MK93V/update",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/resource/01HNZXA1BX9B297CYAAA4MK93V",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/resource/01HNZXA1BX9B297CYAAA4MK93V/delete",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/setting/theming",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/setting/general",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/setting/mail",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/tag/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/tag/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/tag/01HNP0TTQNTR03J7ZQHR09YMJJ/edit",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/tag/01HNP0TTQNTR03J7ZQHR09YMJJ/delete",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/user/login",
        no_session=200,
        admin=302,
        user=302,
        moderator=302,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/user/new_user",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/perfil",
        no_session=302,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/users/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/setting/adsense",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Root page (same as /home)
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/",
        admin=200,
        no_session=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[
            "NOW LMS".encode("utf-8"),
            "Aplicación para gestión del aprendizaje.".encode("utf-8"),
            "Sistema de aprendizaje en linea.".encode("utf-8"),
        ],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Ads.txt for advertising platforms
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/ads.txt",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/http/error/403",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/http/error/404",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Password recovery and mail routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/user/forgot_password",
        no_session=200,
        admin=302,
        user=302,
        moderator=302,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # Additional user routes in URL map order
    # Note: Token routes commented out as they cause JWT decode errors with sample tokens
    # Ruta(
    #     ruta="/user/check_mail/sample-token",
    #     no_session=404,  # Invalid token will return 404
    #     admin=404,
    #     user=404,
    #     moderator=404,
    #     instructor=404,
    #     texto=[],
    #     como_user=[],
    #     como_moderador=[],
    #     como_instructor=[],
    #     como_admin=[],
    # ),
    Ruta(
        ruta="/user/messages",
        no_session=302,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # Ruta(
    #     ruta="/user/reset_password/sample-token",
    #     no_session=404,  # Invalid token will return 404
    #     admin=404,
    #     user=404,
    #     moderator=404,
    #     instructor=404,
    #     texto=[],
    #     como_user=[],
    #     como_moderador=[],
    #     como_instructor=[],
    #     como_admin=[],
    # ),
    # <---------------------------------------------------------------------> #
    # Admin announcements routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/admin/announcements",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/announcements/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/announcements/1/edit",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/announcements/1/delete",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/announcements/2/delete",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Admin blog management routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/admin/blog",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/blog/posts/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/blog/tags",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/admin/flagged-messages",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Admin user management routes
    # <---------------------------------------------------------------------> #
    # Note: Commented out temporarily - these routes redirect and need more investigation
    # Ruta(
    #     ruta="/admin/user/change_type",
    #     no_session=302,
    #     admin=200,
    #     user=403,
    #     moderator=403,
    #     instructor=403,
    #     texto=[],
    #     como_user=[],
    #     como_moderador=[],
    #     como_instructor=[],
    #     como_admin=[],
    # ),
    Ruta(
        ruta="/admin/users/list_inactive",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Blog public routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/blog",
        no_session=200,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Certificate advanced routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/certificate/issued/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/certificate/release/",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Dashboard routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/dashboard/announcements",
        no_session=302,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Student dashboard routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/student",
        no_session=302,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Instructor dashboard routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/instructor",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/instructor/announcements",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/instructor/announcements/new",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/instructor/blog",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/instructor/evaluaciones",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/instructor/group/list",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/instructor/nueva-evaluacion",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Moderator dashboard routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/moderator",
        no_session=302,
        admin=302,
        user=302,
        moderator=302,
        instructor=302,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Message system routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/message/new",
        no_session=302,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/message/report/",
        no_session=302,
        admin=200,
        user=200,
        moderator=200,
        instructor=200,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # <---------------------------------------------------------------------> #
    # Additional settings routes
    # <---------------------------------------------------------------------> #
    # Ruta(
    #    ruta="/setting/delete_site_logo",
    #    no_session=302,
    #    admin=302,
    #    user=403,
    #    moderator=403,
    #    instructor=403,
    #    texto=[],
    #    como_user=[],
    #    como_moderador=[],
    #    como_instructor=[],
    #    como_admin=[],
    # ),
    Ruta(
        ruta="/setting/mail/verify",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/setting/mail_check",
        no_session=302,
        admin=302,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/setting/paypal",
        no_session=302,
        admin=200,
        user=403,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    # Ruta(
    #     ruta="/setting/stripe",
    #     no_session=302,
    #     admin=200,
    #     user=403,
    #     moderator=403,
    #     instructor=403,
    #     texto=[],
    #     como_user=[],
    #     como_moderador=[],
    #     como_instructor=[],
    #     como_admin=[],
    # ),
    # <---------------------------------------------------------------------> #
    # Profile management routes
    # <---------------------------------------------------------------------> #
    Ruta(
        ruta="/perfil/01HNZXJRD65A55BJACFEFNZ88D/delete_logo",  # student1 ID
        no_session=302,
        admin=403,
        user=302,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/perfil/edit/01HNZXJRD65A55BJACFEFNZ88D",  # student1 ID
        no_session=302,
        admin=403,
        user=200,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
    Ruta(
        ruta="/perfil/cambiar_contraseña/01HNZXJRD65A55BJACFEFNZ88D",  # student1 ID
        no_session=302,
        admin=403,
        user=200,
        moderator=403,
        instructor=403,
        texto=[],
        como_user=[],
        como_moderador=[],
        como_instructor=[],
        como_admin=[],
    ),
]
