"""Add public api and recertification support

Revision ID: 1780403775
Revises:
Create Date: 2026-06-02 12:36:15.581352

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1780403775"
down_revision = "20260119_121758"
branch_labels = ("default",)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_api_keys",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("allowed_origin", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("creado", sa.Date(), nullable=False),
        sa.Column("creado_por", sa.String(length=150), nullable=True),
        sa.Column("modificado", sa.DateTime(), nullable=True),
        sa.Column("modificado_por", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_external_api_keys_id"), "external_api_keys", ["id"], unique=False)
    op.create_index(op.f("ix_external_api_keys_key_hash"), "external_api_keys", ["key_hash"], unique=False)

    op.create_table(
        "remote_enrollment_requests",
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("course_code", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("payment_confirmed", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("response_message", sa.Text(), nullable=True),
        sa.Column("api_key_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=150), nullable=True),
        sa.Column("enrollment_id", sa.String(length=26), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("raw_payload_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("creado", sa.Date(), nullable=False),
        sa.Column("creado_por", sa.String(length=150), nullable=True),
        sa.Column("modificado", sa.DateTime(), nullable=True),
        sa.Column("modificado_por", sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["external_api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["estudiante_curso.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usuario.usuario"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_remote_enrollment_requests_id"), "remote_enrollment_requests", ["id"], unique=False)
    op.create_index(
        op.f("ix_remote_enrollment_requests_request_id"), "remote_enrollment_requests", ["request_id"], unique=True
    )

    with op.batch_alter_table("curso", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recertification_required", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("recertification_period_years", sa.Integer(), nullable=True))

    with op.batch_alter_table("certificacion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("expires_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificacion", schema=None) as batch_op:
        batch_op.drop_column("expires_at")

    with op.batch_alter_table("curso", schema=None) as batch_op:
        batch_op.drop_column("recertification_period_years")
        batch_op.drop_column("recertification_required")

    op.drop_index(op.f("ix_remote_enrollment_requests_request_id"), table_name="remote_enrollment_requests")
    op.drop_index(op.f("ix_remote_enrollment_requests_id"), table_name="remote_enrollment_requests")
    op.drop_table("remote_enrollment_requests")
    op.drop_index(op.f("ix_external_api_keys_key_hash"), table_name="external_api_keys")
    op.drop_index(op.f("ix_external_api_keys_id"), table_name="external_api_keys")
    op.drop_table("external_api_keys")
    # ### end Alembic commands ###
