name: Databases

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  multiple_db_check:
    name: Test with multiple databases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # Keep in sync in the python version in the Dockerfile
      - name: Install python package
        env:
          CI: True
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r development.txt
          python -m pip install -e .
          python -m pip install psycopg2-binary
      - name: Test with SQLite
        env:
          CI: True
        run: |
          SECRET_KEY=ASD123klja+AddS lmsctl db-init
      - name: Test with Postgresql + psycopg2
        env:
          CI: True
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE USER lmsctl1 WITH PASSWORD 'lmsctl1';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON SCHEMA public TO lmsctl1;"
          sudo -u postgres psql -c "CREATE DATABASE lmsctl1;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE lmsctl1 TO lmsctl1;"
          sudo -u postgres psql -c "ALTER DATABASE lmsctl1 OWNER TO lmsctl1;"
          sudo -u postgres psql -c "ALTER ROLE lmsctl1 CREATEDB;"
          sudo -u postgres psql -c "GRANT USAGE ON SCHEMA public TO lmsctl1;"
          sudo -u postgres psql -c "GRANT CREATE ON SCHEMA public TO lmsctl1;"
          SECRET_KEY=ASD123klja+AddS CACAO_DB=postgresql+psycopg2://lmsctl1:lmsctl1@localhost/lmsctl1 lmsctl db-init
      - name: Test with Postgresql + pg8000
        env:
          CI: True
        run: |
          sudo -u postgres psql -c "CREATE USER lmsctl2 WITH PASSWORD 'lmsctl2';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON SCHEMA public TO lmsctl2;"
          sudo -u postgres psql -c "CREATE DATABASE lmsctl2;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE lmsctl2 TO lmsctl2;"
          sudo -u postgres psql -c "ALTER DATABASE lmsctl2 OWNER TO lmsctl2;"
          sudo -u postgres psql -c "ALTER ROLE lmsctl2 CREATEDB;"
          sudo -u postgres psql -c "GRANT USAGE ON SCHEMA public TO lmsctl2;"
          sudo -u postgres psql -c "GRANT CREATE ON SCHEMA public TO lmsctl2;"
          SECRET_KEY=ASD123klj+aAddS CACAO_DB=postgresql+pg8000://lmsctl2:lmsctl2@localhost/lmsctl2 lmsctl db-init
