name: Databases

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  multiple_db_check:
    name: Test with multiple databases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # Keep in sync in the python version in the Dockerfile
      - name: Install python package
        env:
          CI: True
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e python-coveralls coveralls
          python -m pip install -r test.txt
      - name: Test package
        env:
          CI: True
          SECRET_KEY: ASD123klj+aAddSskadjandsASVNASJVNSAJIDVSVIAO
        run: |
          pytest  -v --exitfirst --slow=True
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
