name: Publish to PyPi

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install build
        run: |
          python -m pip install build wheel
      - name: Build a binary wheel and a source tarball
        run: |
          cd now_lms/static
          npm install
          cd ..
          cd ..
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
