name: Publish to PyPi

on:
  push:
    branches: [ main, editable_forms ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install build
      run: |
        python -m pip install build wheel
    - name: Build a binary wheel and a source tarball
      run: |
        cd now_lms/static
        npm install 
        cd ..
        cd ..
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution to PyPI
      if: contains(github.event.head_commit.message, 'release:')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
