# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install bandit flake8 pytest
        python -m pip install -r development.txt
    - name: Lint python code
      run: |
        rm -rf build
        flake8 --ignore=E712 now_lms
        python -m build
        python -m twine check dist/*
        python -m bandit -r now_lms
        python -m flake8 now_lms
        python -m pylint now_lms
    - name: Lint html templanes
      run: |
        python -m pip install curlylint
        python -m curlylint now_lms/templates/
    - name: Test with pytest
      run: |
        pytest  -v --exitfirst --cov=now_lms
    - name: Check python  types
      run: |
        python -m pip install mypy
        python -m mypy --install-types --non-interactive now_lms
    - name: OCI Image
      run: |
        docker buildx build .
    - name: Codecov
      uses: codecov/codecov-action@v1
