# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, development, test-db ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: mysqldb
          MYSQL_DATABASE: mysqldb
          MYSQL_USER: mysqldb
          MYSQL_PASSWORD: mysqldb
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgresdb
          POSTGRES_USER: postgresdb
          POSTGRES_PASSWORD: postgresdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install bandit flake8 pytest
        python -m pip install -r development.txt
    - name: Lint python code
      run: |
        rm -rf build
        flake8 --ignore=E712 now_lms
        python -m build
        python -m twine check dist/*
        python -m bandit -r now_lms
        python -m flake8 now_lms
        python -m pylint now_lms
    - name: Lint html templanes
      run: |
        python -m pip install curlylint
        python -m curlylint now_lms/templates/
    - name: Test with pytest/SQLite
      run: |
        pytest  -v --exitfirst --cov=now_lms
    - name: Test with pytest/Postgres
      run: |
        DATABASE_URL=postgresql://postgresdb:postgresdb@postgres:5432/postgresdb pytest  -v --exitfirst --cov=now_lms
    - name: Test with pytest/MySQL
      run: |
        DATABASE_URL=mysql://mysqldb:mysqldb@mysql:3306/mysqldb pytest  -v --exitfirst --cov=now_lms
    - name: Check python  types
      run: |
        python -m pip install mypy
        python -m mypy --install-types --non-interactive now_lms
    - name: Codecov
      uses: codecov/codecov-action@v1
