name: Release Validation

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    multiple_db_check:
        name: Test with multiple databases
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12 # Keep in sync in the python version in the Dockerfile
            - name: Install python package
              env:
                  CI: True
                  LOG_LEVEL: TRACE
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r test.txt
                  python -m pip install -e .
                  python -m pip install mysql-connector-python
            - name: Test with SQLite
              env:
                  CI: True
                  SECRET_KEY: ASD123klj+aAddSadadadadafafsaggsdfsfdasf
                  LOG_LEVEL: TRACE
              run: |
                  pybabel compile -d now_lms/translations
                  pytest --cov=now_lms
            - name: Test with MySQL
              env:
                  CI: True
                  SECRET_KEY: ASD123klj+aAddS
                  DATABASE_URL: mysql://lmsctl:lmsctl@127.0.0.1/lmsctl
                  ADMIN_USER: hello
                  ADMIN_PSWD: world
                  FLASK_APP: now_lms
                  LOG_LEVEL: TRACE
              run: |
                  sudo systemctl start mysql.service
                  mysql -u root -proot -e "CREATE USER 'lmsctl'@'localhost' IDENTIFIED BY 'lmsctl';"
                  mysql -u root -proot -e "CREATE DATABASE lmsctl;"
                  mysql -u root -proot -e "GRANT ALL PRIVILEGES ON lmsctl.* TO 'lmsctl'@'localhost'; FLUSH PRIVILEGES;"
                  pytest -v -v --cov=now_lms --cov-append tests/test_multipledb.py

            - name: Test with Postgresql + pg8000
              env:
                  CI: True
                  SECRET_KEY: ASD123klj+aAddSASGGSGSGSGSGSSDFASFASFAFASASaggggdgdgds
                  DATABASE_URL: postgresql+pg8000://lmsctl2:lmsctl2@127.0.0.1:5432/lmsctl2
                  ADMIN_USER: hello
                  ADMIN_PSWD: world
                  FLASK_APP: now_lms
                  LOG_LEVEL: TRACE
              run: |
                  sudo systemctl start postgresql.service
                  sudo -u postgres psql -c "CREATE USER lmsctl2 WITH PASSWORD 'lmsctl2';"
                  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON SCHEMA public TO lmsctl2;"
                  sudo -u postgres psql -c "CREATE DATABASE lmsctl2;"
                  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE lmsctl2 TO lmsctl2;"
                  sudo -u postgres psql -c "ALTER DATABASE lmsctl2 OWNER TO lmsctl2;"
                  sudo -u postgres psql -c "ALTER ROLE lmsctl2 CREATEDB;"
                  sudo -u postgres psql -c "GRANT USAGE ON SCHEMA public TO lmsctl2;"
                  sudo -u postgres psql -c "GRANT CREATE ON SCHEMA public TO lmsctl2;"
                  pytest  -v -v  --cov=now_lms --cov-append tests/test_multipledb.py
            - name: Linting
              run: |
                  flake8 --max-line-length=120 --ignore=E501,E203,E266,W503,E722 now_lms
                  mypy now_lms --install-types --non-interactive --ignore-missing-imports
                  ruff check now_lms
                  pylint now_lms --score=yes --fail-under=9
            - uses: codecov/codecov-action@v5
              with:
                  fail_ci_if_error: true # optional (default = false)
                  #files: ./coverage1.xml,./coverage2.xml # optional
                  flags: unittests # optional
                  name: codecov-umbrella # optional
                  token: ${{ secrets.CODECOV_TOKEN }}
                  verbose: true # optional (default = false)
