name: CI

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main, development]

jobs:
    build:
        name: Build check (Python ${{ matrix.python-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.11, 3.12, 3.13, 3.14]
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.6.0
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --require-hashes -r test.lock
            - name: Check python package
              run: |
                  python -m build
                  python -m twine check dist/*

    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7
            - name: Set up Python 3
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.6.0
              with:
                  python-version: 3.12
            - name: Install python package
              run: |
                  python -m pip install --require-hashes -r test.lock
            - name: Linting
              run: |
                  flake8 --max-line-length=120 --ignore=E501,E203,E266,W503,E722 now_lms
                  mypy now_lms --install-types --non-interactive --ignore-missing-imports
                  ruff check now_lms
                  pylint now_lms --score=yes --fail-under=9

    test-sqlite:
        name: Test with SQLite
        runs-on: ubuntu-latest
        env:
            TEST_SECRET_KEY: ASD123klj+aAddSadadadadafafsaggsdfsfdasf
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7
            - name: Set up Python 3
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.6.0
              with:
                  python-version: 3.12
            - name: Install python package
              env:
                  CI: True
              run: |
                  python -m pip install --require-hashes -r test.lock
            - name: Test with SQLite
              env:
                  CI: True
                  SECRET_KEY: ${{ env.TEST_SECRET_KEY }}
              run: |
                  pybabel compile -d now_lms/translations
                  pytest --cov=now_lms
            - uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
              with:
                  fail_ci_if_error: true
                  flags: unittests
                  name: codecov-sqlite
                  token: ${{ secrets.CODECOV_TOKEN }}
                  verbose: true

    test-postgresql:
        name: Test with PostgreSQL
        runs-on: ubuntu-latest
        env:
            TEST_SECRET_KEY: ASD123klj+aAddSadadadadafafsaggsdfsfdasf
            TEST_ADMIN_USER: hello
            TEST_ADMIN_PASSWORD: world
            POSTGRES_PASSWORD: lmsctl2
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7
            - name: Set up Python 3
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.6.0
              with:
                  python-version: 3.12
            - name: Install python package
              env:
                  CI: True
              run: |
                  python -m pip install --require-hashes -r test.lock
            - name: Setup PostgreSQL
              run: |
                  sudo systemctl start postgresql.service
                  sudo -u postgres psql -c "CREATE USER lmsctl2 WITH PASSWORD '${{ env.POSTGRES_PASSWORD }}';"
                  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON SCHEMA public TO lmsctl2;"
                  sudo -u postgres psql -c "CREATE DATABASE lmsctl2;"
                  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE lmsctl2 TO lmsctl2;"
                  sudo -u postgres psql -c "ALTER DATABASE lmsctl2 OWNER TO lmsctl2;"
                  sudo -u postgres psql -c "ALTER ROLE lmsctl2 CREATEDB;"
                  sudo -u postgres psql -c "GRANT USAGE ON SCHEMA public TO lmsctl2;"
                  sudo -u postgres psql -c "GRANT CREATE ON SCHEMA public TO lmsctl2;"
            - name: Test with PostgreSQL
              env:
                  CI: True
                  SECRET_KEY: ${{ env.TEST_SECRET_KEY }}
                  DATABASE_URL: postgresql+pg8000://lmsctl2:${{ env.POSTGRES_PASSWORD }}@127.0.0.1:5432/lmsctl2
                  ADMIN_USER: ${{ env.TEST_ADMIN_USER }}
                  ADMIN_PSWD: ${{ env.TEST_ADMIN_PASSWORD }}
                  FLASK_APP: now_lms
              run: |
                  pytest -v -v --cov=now_lms tests/test_multipledb.py
                  pytest -v -v --cov=now_lms --cov-append tests/test_alembic_upgrade.py
            - uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
              with:
                  fail_ci_if_error: true
                  flags: unittests
                  name: codecov-postgresql
                  token: ${{ secrets.CODECOV_TOKEN }}
                  verbose: true

    test-mysql:
        name: Test with MySQL
        runs-on: ubuntu-latest
        env:
            TEST_SECRET_KEY: ASD123klj+aAddSadadadadafafsaggsdfsfdasf
            TEST_ADMIN_USER: hello
            TEST_ADMIN_PASSWORD: world
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: lmsctl
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7
            - name: Set up Python 3
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.6.0
              with:
                  python-version: 3.12
            - name: Install python package
              env:
                  CI: True
              run: |
                  python -m pip install --require-hashes -r test.lock
            - name: Setup MySQL
              run: |
                  sudo systemctl start mysql.service
                  mysql -u root -p"${{ env.MYSQL_ROOT_PASSWORD }}" -e "CREATE USER 'lmsctl'@'localhost' IDENTIFIED BY '${{ env.MYSQL_PASSWORD }}';"
                  mysql -u root -p"${{ env.MYSQL_ROOT_PASSWORD }}" -e "CREATE DATABASE lmsctl;"
                  mysql -u root -p"${{ env.MYSQL_ROOT_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON lmsctl.* TO 'lmsctl'@'localhost'; FLUSH PRIVILEGES;"
            - name: Test with MySQL
              env:
                  CI: True
                  SECRET_KEY: ${{ env.TEST_SECRET_KEY }}
                  DATABASE_URL: mysql+mysqlconnector://lmsctl:${{ env.MYSQL_PASSWORD }}@127.0.0.1/lmsctl
                  ADMIN_USER: ${{ env.TEST_ADMIN_USER }}
                  ADMIN_PSWD: ${{ env.TEST_ADMIN_PASSWORD }}
                  FLASK_APP: now_lms
              run: |
                  pytest -v -v --cov=now_lms tests/test_multipledb.py
                  pytest -v -v --cov=now_lms --cov-append tests/test_alembic_upgrade.py
            - uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
              with:
                  fail_ci_if_error: true
                  flags: unittests
                  name: codecov-mysql
                  token: ${{ secrets.CODECOV_TOKEN }}
                  verbose: true
